services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vemco_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
      - redis
    networks:
      - vemco_network

  nginx:
    image: nginx:alpine
    container_name: vemco_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - vemco_network

  mysql:
    image: mysql:8.0
    container_name: vemco_mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: vemco_challenge
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
      MYSQL_USER: vemco
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - vemco_network

  redis:
    image: redis:alpine
    container_name: vemco_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - vemco_network

networks:
  vemco_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
